# -*- coding: utf-8 -*-
"""FindingRice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtN_CC6ik-cle6QFLEnZdWko1hbu05bk
"""

# ==============================================================================
# 🚀 Module 1: Unified YOLOv8 Training System (Economy Rice Smart Checkout)
# ==============================================================================

# 1. Environment Setup
print("🚀 Installing YOLOv8 environment...")
!pip install ultralytics -q  # Uncomment if running in a fresh Colab environment

import os
import shutil
import yaml
import glob
import zipfile
from ultralytics import YOLO

# ---------------------------------------------------------
# ⚙️ Configuration Area
# ---------------------------------------------------------
# Name of your zip file (without the .zip extension)
DATASET_NAME = 'food_dataset'

# ⚠️ CRITICAL: The order of these classes MUST match the class IDs in your Roboflow export!
# Updated to include the 'plate' class based on your latest dataset requirements.
# Assuming YOLO uses 0-indexing (0=meat, 1=rice, 2=vege, 3=plate)
CLASSES = ['meat', 'rice', 'vege', 'plate']

# ---------------------------------------------------------

ZIP_PATH = f'/content/{DATASET_NAME}.zip'
DATASET_DIR = f'/content/{DATASET_NAME}'

print(f"\n\n{'='*50}")
print(f"🔥 Initializing Multi-Class Unified Training Pipeline")
print(f"{'='*50}")

# Clean up old data to prevent conflicts
if os.path.exists(DATASET_DIR):
    shutil.rmtree(DATASET_DIR)

# Safe Extraction
if not os.path.exists(ZIP_PATH):
    print(f"❌ Error: {ZIP_PATH} not found! Please check if it is uploaded in the left panel.")
else:
    print(f"📦 Safely extracting {DATASET_NAME}.zip ...")
    # Replaced OS command with native Python zipfile for better stability
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(DATASET_DIR)

    # Smartly locate the images directory
    train_dir = None
    val_dir = None

    for root, dirs, _ in os.walk(DATASET_DIR):
        if 'images' in dirs:
            full_path = os.path.join(root, 'images')
            if 'train' in root:
                train_dir = full_path
            elif 'valid' in root or 'val' in root:
                val_dir = full_path

    # Fallback search strategy
    if not train_dir:
        potentials = glob.glob(f"{DATASET_DIR}/**/train/images", recursive=True)
        if potentials: train_dir = potentials[0]

    if not val_dir and train_dir:
        print(f"⚠️ Warning: Validation set (valid/val) not found. Using training set as fallback.")
        val_dir = train_dir

    if not train_dir:
        print(f"❌ Fatal Error: Could not find 'train/images' folder in the zip file! Please check dataset structure.")
    else:
        # Generate the data.yaml configuration file required by YOLO
        yaml_path = os.path.join(DATASET_DIR, 'data_custom.yaml')
        yaml_content = {
            'path': DATASET_DIR,
            'train': train_dir,
            'val': val_dir,
            'nc': len(CLASSES),     # Automatically calculate number of classes (4)
            'names': CLASSES        # Map the class names
        }

        with open(yaml_path, 'w') as f:
            yaml.dump(yaml_content, f)

        print(f"✅ Configuration file generated successfully with {len(CLASSES)} classes.")

        # Begin Training
        print(f"🔥 Starting model training (Max 200 epochs)...")
        try:
            model = YOLO('yolov8n.pt') # Initialize YOLOv8 Nano for object detection

            model.train(
                data=yaml_path,
                epochs=200,           # Maximum training epochs
                patience=20,          # Stop early if no improvement after 20 epochs
                imgsz=640,
                plots=False,
                name="train_food_all" # Directory name for saved run logs
            )

            # Extract the best model weights
            best_weights = glob.glob('/content/runs/detect/train_food_all*/weights/best.pt')

            if best_weights:
                # Get the most recently generated model
                target = max(best_weights, key=os.path.getctime)
                final_path = '/content/model_mixed_rice.pt'
                shutil.copy(target, final_path)
                print(f"\n🎉 Training successful! Unified model saved at: {final_path}")
                print("You can now download this model for inference testing in the main system!")
            else:
                print("\n❌ Training completed, but weights/best.pt was not found in the runs directory.")

        except Exception as e:
            print(f"\n❌ An error occurred during training: {e}")

# ==============================================================================
# 🚀 Clean Edition: RT-DETR Automated Training Script (Training Only)
# ==============================================================================
import os
import shutil
import glob
from ultralytics import RTDETR

print(f"\n{'='*80}")
print("🔥 Starting RT-DETR Pure Training Pipeline")
print(f"{'='*80}")

# --- Configuration ---
yaml_path = '/content/food_dataset/data_custom.yaml'
best_rtdetr_model_path = '/content/model_rtdetr_mixed_rice.pt'

if not os.path.exists(yaml_path):
    print(f"❌ Error: {yaml_path} not found! Please ensure the dataset is extracted and the YAML is generated.")
else:
    print("🔄 Loading RT-DETR pre-trained Large model (rtdetr-l.pt)...")
    try:
        # Initialize the RT-DETR model (Transformer-based architecture)
        model = RTDETR('rtdetr-l.pt')

        # Begin Training
        print("🔥 Starting model training (Max 200 epochs)...")
        model.train(
            data=yaml_path,
            epochs=200,
            patience=20,          # 🌟 IMPROVEMENT: Added Early Stopping to prevent overfitting/wasting time!
            imgsz=640,
            plots=False,
            name="train_food_rtdetr"
        )

        # Extract and save the best model weights
        best_weights = glob.glob('/content/runs/detect/train_food_rtdetr*/weights/best.pt')

        if best_weights:
            # Locate the most recently generated 'best.pt' file
            target = max(best_weights, key=os.path.getctime)
            shutil.copy(target, best_rtdetr_model_path)
            print(f"\n🎉 RT-DETR Training Successful! Model saved as: {best_rtdetr_model_path}")
        else:
            print("\n❌ Training completed, but weights/best.pt was not found.")

    except Exception as e:
        print(f"\n❌ RT-DETR Training Error: {e}")

# ==============================================================================
# 🚀 Module 1 & 2: Faster R-CNN PyTorch Training & Inference Pipeline
# ==============================================================================
import os
import zipfile
import glob
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from google.colab import files

print(f"\n{'='*60}")
print("🔥 Initializing Faster R-CNN (Two-Stage Detector) System")
print(f"{'='*60}")

# ---------------------------------------------------------
# ⚙️ Configuration Area
# ---------------------------------------------------------
DATASET_NAME = 'food_dataset'
ZIP_PATH = f'/content/{DATASET_NAME}.zip'
DATASET_DIR = f'/content/{DATASET_NAME}'

# ⚠️ MUST match the YOLO label order (0=meat, 1=rice, 2=vege, 3=plate)
# because Faster R-CNN training reads class IDs from YOLO label files directly.
CLASSES = ['meat', 'rice', 'vege', 'plate']
NUM_CLASSES = len(CLASSES) + 1  # PyTorch requires +1 for the 'background' class

BASE_PRICES = {'meat': 4.00, 'rice': 1.50, 'vege': 2.00}
CURRENCY = "RM"
SIZE_MULTIPLIERS = {'S': 0.7, 'M': 1.0, 'L': 1.5}
COLORS = {'rice': (0, 255, 0), 'vege': (255, 0, 0), 'meat': (0, 0, 255), 'plate': (0, 255, 255)}

# --- 1. Dataset Extraction ---
if not os.path.exists(ZIP_PATH):
    print(f"❌ Error: {ZIP_PATH} not found! Please upload your dataset zip to the left panel.")
else:
    if not os.path.exists(DATASET_DIR):
        print(f"📦 Extracting {DATASET_NAME}.zip ...")
        with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
            zip_ref.extractall(DATASET_DIR)

# Find train images (dynamically locates the folder)
train_images_dir = glob.glob(f"{DATASET_DIR}/**/train/images", recursive=True)[0]
train_labels_dir = train_images_dir.replace('images', 'labels')

# --- 2. Custom PyTorch Dataset (Robust YOLO to Faster R-CNN format) ---
class YOLODataset(Dataset):
    def __init__(self, img_dir, label_dir):
        self.img_dir = img_dir
        self.label_dir = label_dir
        self.imgs = [img for img in os.listdir(img_dir) if img.endswith(('.jpg', '.png', '.jpeg'))]

    def __getitem__(self, idx):
        img_name = self.imgs[idx]
        img_path = os.path.join(self.img_dir, img_name)

        # Load image
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        height, width, _ = img.shape
        img_tensor = torch.as_tensor(img, dtype=torch.float32).permute(2, 0, 1) / 255.0

        # Load labels
        label_path = os.path.join(self.label_dir, os.path.splitext(img_name)[0] + '.txt')
        boxes, labels = [], []

        if os.path.exists(label_path):
            with open(label_path, 'r') as f:
                for line in f.readlines():
                    parts = line.strip().split()
                    if not parts: continue

                    class_id = int(parts[0])

                    if len(parts) == 5:
                        # Format 1: Standard YOLO Bounding Box (class, xc, yc, w, h)
                        _, x_center, y_center, w, h = map(float, parts)
                        xmin = (x_center - w/2) * width
                        xmax = (x_center + w/2) * width
                        ymin = (y_center - h/2) * height
                        ymax = (y_center + h/2) * height
                    else:
                        # Format 2: YOLO Segmentation Polygon -> Convert to Bounding Box
                        coords = list(map(float, parts[1:]))
                        x_coords = coords[0::2]
                        y_coords = coords[1::2]

                        xmin = min(x_coords) * width
                        xmax = max(x_coords) * width
                        ymin = min(y_coords) * height
                        ymax = max(y_coords) * height

                    # Ensure bounding box coordinates stay within image boundaries
                    xmin, ymin = max(0, xmin), max(0, ymin)
                    xmax, ymax = min(width, xmax), min(height, ymax)

                    # Only append if valid dimensions
                    if xmax > xmin and ymax > ymin:
                        boxes.append([xmin, ymin, xmax, ymax])
                        labels.append(class_id + 1) # Shift class ID by 1 for background

        target = {}
        target["boxes"] = torch.as_tensor(boxes, dtype=torch.float32) if len(boxes) > 0 else torch.zeros((0, 4), dtype=torch.float32)
        target["labels"] = torch.as_tensor(labels, dtype=torch.int64) if len(labels) > 0 else torch.zeros((0,), dtype=torch.int64)
        return img_tensor, target

    def __len__(self):
        return len(self.imgs)

# Helper function to collate batches for DataLoader
def collate_fn(batch): return tuple(zip(*batch))

# --- 3. Model Setup & Training Loop ---
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(f"⚡ Using device: {device}")

# Load pre-trained Faster R-CNN with ResNet50 backbone
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights="DEFAULT")
in_features = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, NUM_CLASSES)
model.to(device)

print("\n🚀 Preparing Dataset Loaders...")
train_dataset = YOLODataset(train_images_dir, train_labels_dir)
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=collate_fn)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

# Keep epochs relatively low for initial testing
EPOCHS = 200
print(f"🔥 Starting PyTorch Training Loop for {EPOCHS} Epochs...")

for epoch in range(EPOCHS):
    model.train()
    epoch_loss = 0
    for images, targets in train_loader:
        images = list(image.to(device) for image in images)
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        loss_dict = model(images, targets)
        losses = sum(loss for loss in loss_dict.values())

        optimizer.zero_grad()
        losses.backward()
        optimizer.step()
        epoch_loss += losses.item()

    print(f"Epoch {epoch+1}/{EPOCHS} - Loss: {epoch_loss/len(train_loader):.4f}")

torch.save(model.state_dict(), '/content/faster_rcnn_mixed_rice.pth')
print("✅ Training Complete! Model saved as faster_rcnn_mixed_rice.pth")

# ==============================================================================
# 🚀 Module 4: Smart Checkout Inference System
#    (Economy Rice Smart Checkout — Multi-Model Support)
# ==============================================================================
#
# Supports all 3 trained models:
#   - YOLOv8       → model_mixed_rice.pt
#   - RT-DETR      → model_rtdetr_mixed_rice.pt
#   - Faster R-CNN → faster_rcnn_mixed_rice.pth
#
# Features:
#   - Auto-detect model type from file extension / architecture
#   - Smart portion size estimation (S / M / L) based on bbox area
#   - Dynamic pricing with quantity multipliers
#   - Visual receipt overlay on image
#   - Printable text receipt
#   - Batch inference on folder of images
#   - Confidence filtering & NMS deduplication
#   - Side-by-side comparison of multiple models
#   - Cropping each detected food item for visual inspection
# ==============================================================================

# ── 1. Environment Setup ─────────────────────────────────────────────────────

print("🚀 Setting up Smart Checkout environment...")

import os
import cv2
import time
import torch
import numpy as np
import math
import glob
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from datetime import datetime
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple

import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from IPython.display import display, HTML, Image as IPyImage
from google.colab import files as colab_files

# ── 2. Configuration ─────────────────────────────────────────────────────────

CONFIG = {
    # ── Class definitions ─────────────────────────────────────────────────
    # MUST match the class order used during training
    "classes": ["meat", "plate", "rice", "vege"],

    # ── Pricing (RM) ──────────────────────────────────────────────────────
    "currency": "RM",
    "base_prices": {
        "meat": 4.00,
        "rice": 1.50,
        "vege": 2.00,
        "plate": 0.00,   # plate is not charged
    },
    "size_multipliers": {
        "S": 0.7,
        "M": 1.0,
        "L": 1.5,
    },

    # ── Size thresholds ───────────────────────────────────────────────────
    # Portion size is determined by bbox area as a fraction of total image area
    # These percentages define the boundaries between S / M / L
    "size_thresholds": {
        "small_max":  0.04,   # bbox area < 4% of image → Small
        "medium_max": 0.10,   # bbox area < 10% → Medium, >= 10% → Large
    },

    # ── Detection settings ────────────────────────────────────────────────
    "confidence_threshold": 0.40,   # minimum confidence to accept
    "iou_threshold":        0.45,   # NMS IoU threshold for deduplication
    "imgsz":                640,

    # ── Visualization ─────────────────────────────────────────────────────
    "colors": {
        "meat":  (0, 0, 255),     # red
        "rice":  (0, 255, 0),     # green
        "vege":  (255, 165, 0),   # orange
        "plate": (255, 255, 0),   # cyan
    },
    "font_scale":     0.7,
    "box_thickness":  2,
    "receipt_width":  400,   # pixels for receipt panel

    # ── Cropping settings ─────────────────────────────────────────────────
    "crop_padding": 0.10,   # 10% padding around each detected food item

    # ── Model paths (update to match your trained files) ──────────────────
    "yolo_model":      "/content/model_mixed_rice.pt",
    "rtdetr_model":    "/content/model_rtdetr_mixed_rice.pt",
    "frcnn_model":     "/content/faster_rcnn_mixed_rice.pth",
    "frcnn_num_classes": 5,   # 4 classes + 1 background
    "frcnn_backbone":    "resnet50",
}


# ── 3. Data Classes ──────────────────────────────────────────────────────────

@dataclass
class Detection:
    """Single detected food item."""
    class_name: str
    confidence: float
    bbox: Tuple[int, int, int, int]   # (x1, y1, x2, y2)
    area_fraction: float              # bbox area / image area
    size: str                         # S / M / L
    price: float                      # after size multiplier
    cropped_image: Optional[np.ndarray] = None   # cropped region of the detected food


@dataclass
class CheckoutResult:
    """Full checkout result for one image."""
    image_path: str
    model_name: str
    detections: List[Detection] = field(default_factory=list)
    total_price: float = 0.0
    inference_time_ms: float = 0.0
    annotated_image: Optional[np.ndarray] = None

    @property
    def item_summary(self) -> Dict[str, int]:
        """Count of each detected item."""
        return dict(Counter(d.class_name for d in self.detections))

    @property
    def billable_items(self) -> List[Detection]:
        """Items that have a price > 0 (excludes plate)."""
        return [d for d in self.detections if d.price > 0]

    @property
    def cropped_images(self) -> List[Tuple[str, float, np.ndarray]]:
        """List of (class_name, confidence, cropped_image) for all food detections with crops."""
        return [
            (d.class_name, d.confidence, d.cropped_image)
            for d in self.detections
            if d.cropped_image is not None and d.class_name != "plate"
        ]


# ── 4. Size Estimator ────────────────────────────────────────────────────────

def estimate_size(area_fraction: float) -> str:
    """Estimate portion size from bbox area as fraction of image."""
    thresholds = CONFIG["size_thresholds"]
    if area_fraction < thresholds["small_max"]:
        return "S"
    elif area_fraction < thresholds["medium_max"]:
        return "M"
    else:
        return "L"


def calculate_price(class_name: str, size: str) -> float:
    """Calculate price for a single item based on class and size."""
    base = CONFIG["base_prices"].get(class_name, 0.0)
    mult = CONFIG["size_multipliers"].get(size, 1.0)
    return round(base * mult, 2)


# ── 5. Model Loaders ─────────────────────────────────────────────────────────

class YOLODetector:
    """Wrapper for YOLOv8 / RT-DETR (ultralytics API)."""

    def __init__(self, model_path: str, model_type: str = "yolo"):
        from ultralytics import YOLO, RTDETR
        self.model_type = model_type
        if model_type == "rtdetr":
            self.model = RTDETR(model_path)
            self.name = "RT-DETR"
        else:
            self.model = YOLO(model_path)
            self.name = "YOLOv8"
        print(f"  ✅ Loaded {self.name} from {model_path}")

    def predict(self, image: np.ndarray) -> List[Dict]:
        results = self.model.predict(
            source=image,
            conf=CONFIG["confidence_threshold"],
            iou=CONFIG["iou_threshold"],
            imgsz=CONFIG["imgsz"],
            verbose=False,
        )
        detections = []
        if results and len(results) > 0:
            result = results[0]
            for box in result.boxes:
                x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
                conf = float(box.conf[0])
                cls_id = int(box.cls[0])
                cls_name = CONFIG["classes"][cls_id] if cls_id < len(CONFIG["classes"]) else f"class_{cls_id}"
                detections.append({
                    "class_name": cls_name,
                    "confidence": conf,
                    "bbox": (int(x1), int(y1), int(x2), int(y2)),
                })
        return detections


class FasterRCNNDetector:
    """Wrapper for Faster R-CNN (torchvision)."""

    def __init__(self, model_path: str):
        self.name = "Faster R-CNN"
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Build model architecture
        num_classes = CONFIG["frcnn_num_classes"]
        backbone = CONFIG["frcnn_backbone"]
        if backbone == "mobilenet_v3":
            self.model = torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn(weights=None)
        else:
            self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights=None)

        in_features = self.model.roi_heads.box_predictor.cls_score.in_features
        self.model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

        # Load weights
        state_dict = torch.load(model_path, map_location=self.device)
        self.model.load_state_dict(state_dict)
        self.model.to(self.device)
        self.model.eval()
        print(f"  ✅ Loaded Faster R-CNN from {model_path}")

    @torch.no_grad()
    def predict(self, image: np.ndarray) -> List[Dict]:
        img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) if len(image.shape) == 3 else image
        img_tensor = torch.as_tensor(img_rgb, dtype=torch.float32).permute(2, 0, 1) / 255.0
        img_tensor = img_tensor.unsqueeze(0).to(self.device)

        outputs = self.model(img_tensor)[0]

        detections = []
        boxes  = outputs["boxes"].cpu().numpy()
        scores = outputs["scores"].cpu().numpy()
        labels = outputs["labels"].cpu().numpy()

        for box, score, label in zip(boxes, scores, labels):
            if score < CONFIG["confidence_threshold"]:
                continue
            if label == 0:
                continue  # skip background

            cls_idx = label - 1  # Faster R-CNN has +1 offset for background
            cls_name = CONFIG["classes"][cls_idx] if cls_idx < len(CONFIG["classes"]) else f"class_{label}"

            x1, y1, x2, y2 = box.astype(int)
            detections.append({
                "class_name": cls_name,
                "confidence": float(score),
                "bbox": (int(x1), int(y1), int(x2), int(y2)),
            })

        # Manual NMS (torchvision model may already do this, but just in case)
        detections = _nms_filter(detections, CONFIG["iou_threshold"])
        return detections


def _nms_filter(detections: List[Dict], iou_thresh: float) -> List[Dict]:
    """Simple class-aware NMS to remove duplicate boxes."""
    if len(detections) <= 1:
        return detections

    # Group by class
    by_class = defaultdict(list)
    for d in detections:
        by_class[d["class_name"]].append(d)

    filtered = []
    for cls_name, dets in by_class.items():
        dets.sort(key=lambda x: x["confidence"], reverse=True)
        keep = []
        for det in dets:
            overlap = False
            for kept in keep:
                iou = _compute_iou(det["bbox"], kept["bbox"])
                if iou > iou_thresh:
                    overlap = True
                    break
            if not overlap:
                keep.append(det)
        filtered.extend(keep)

    return filtered


def _compute_iou(box1, box2) -> float:
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])
    inter = max(0, x2 - x1) * max(0, y2 - y1)
    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
    union = area1 + area2 - inter
    return inter / union if union > 0 else 0.0


def load_detector(model_path: str) -> object:
    """Auto-detect model type and return appropriate detector."""
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"❌ Model not found: {model_path}")

    ext = Path(model_path).suffix.lower()
    name_lower = Path(model_path).stem.lower()

    if ext == ".pth":
        return FasterRCNNDetector(model_path)
    elif "rtdetr" in name_lower:
        return YOLODetector(model_path, model_type="rtdetr")
    else:
        return YOLODetector(model_path, model_type="yolo")


# ── 6. Cropping Helper ───────────────────────────────────────────────────────

def _crop_detection(image: np.ndarray, bbox: Tuple[int, int, int, int],
                    padding: float = None) -> Optional[np.ndarray]:
    """Crop a detected food item from the image with padding.

    Parameters
    ----------
    image : np.ndarray
        The original (clean) image in BGR or RGB format.
    bbox : tuple
        (x1, y1, x2, y2) bounding box coordinates.
    padding : float, optional
        Fractional padding around the bbox (default from CONFIG).

    Returns
    -------
    np.ndarray or None
        Cropped image region, or None if crop is invalid.
    """
    if padding is None:
        padding = CONFIG["crop_padding"]

    x1, y1, x2, y2 = bbox
    pad_x = int((x2 - x1) * padding)
    pad_y = int((y2 - y1) * padding)

    crop_y1 = max(0, y1 - pad_y)
    crop_y2 = min(image.shape[0], y2 + pad_y)
    crop_x1 = max(0, x1 - pad_x)
    crop_x2 = min(image.shape[1], x2 + pad_x)

    if crop_y2 > crop_y1 and crop_x2 > crop_x1:
        return image[crop_y1:crop_y2, crop_x1:crop_x2].copy()
    return None


# ── 7. Checkout Engine ───────────────────────────────────────────────────────

def checkout(image_path: str, detector, verbose: bool = True) -> CheckoutResult:
    """
    Run detection on a single image and compute the checkout.
    Only 1 plate is detected per image (highest confidence).
    All food items are priced relative to that single plate (subtotal).
    Returns a CheckoutResult with detections, prices, cropped images, and annotated image.
    """
    image = cv2.imread(image_path)
    if image is None:
        raise IOError(f"❌ Cannot read image: {image_path}")

    img_h, img_w = image.shape[:2]
    img_area = img_h * img_w

    # Keep a clean copy for cropping (before annotations are drawn)
    img_clean = image.copy()

    # Run inference
    t0 = time.time()
    raw_detections = detector.predict(image)
    inference_ms = (time.time() - t0) * 1000

    # ── Separate plate detections from food detections ──
    # Keep only the single highest-confidence plate
    best_plate = None
    best_plate_conf = 0.0
    food_raws = []

    for raw in raw_detections:
        if raw["class_name"] == "plate":
            if raw["confidence"] > best_plate_conf:
                best_plate_conf = raw["confidence"]
                best_plate = raw
        else:
            food_raws.append(raw)

    # Build Detection objects with size + price + cropped image
    detections = []

    # Add the single plate detection (if found)
    if best_plate is not None:
        x1, y1, x2, y2 = best_plate["bbox"]
        bbox_area = (x2 - x1) * (y2 - y1)
        area_frac = bbox_area / img_area
        detections.append(Detection(
            class_name="plate",
            confidence=best_plate["confidence"],
            bbox=best_plate["bbox"],
            area_fraction=area_frac,
            size="–",
            price=0.0,
            cropped_image=None,
        ))

    # Add food detections
    for raw in food_raws:
        x1, y1, x2, y2 = raw["bbox"]
        bbox_area = (x2 - x1) * (y2 - y1)
        area_frac = bbox_area / img_area

        size  = estimate_size(area_frac)
        price = calculate_price(raw["class_name"], size)

        # Crop the detected food item
        cropped = _crop_detection(img_clean, raw["bbox"])

        detections.append(Detection(
            class_name=raw["class_name"],
            confidence=raw["confidence"],
            bbox=raw["bbox"],
            area_fraction=area_frac,
            size=size,
            price=price,
            cropped_image=cropped,
        ))

    # Sort: plate first, then by class name
    detections.sort(key=lambda d: (d.class_name != "plate", d.class_name, -d.confidence))

    # Subtotal = sum of all food items on this single plate
    subtotal = sum(d.price for d in detections)

    # Annotate image
    annotated = _draw_detections(image.copy(), detections)

    # Build receipt panel
    receipt_panel = _draw_receipt(detections, subtotal, detector.name, inference_ms, img_h)

    # Combine image + receipt side by side
    combined = _combine_image_receipt(annotated, receipt_panel)

    result = CheckoutResult(
        image_path=image_path,
        model_name=detector.name,
        detections=detections,
        total_price=subtotal,
        inference_time_ms=inference_ms,
        annotated_image=combined,
    )

    if verbose:
        _print_receipt(result)

    return result


# ── 8. Visualization ─────────────────────────────────────────────────────────

def _draw_detections(image: np.ndarray, detections: List[Detection]) -> np.ndarray:
    """Draw bounding boxes and labels on the image."""
    for det in detections:
        x1, y1, x2, y2 = det.bbox
        color = CONFIG["colors"].get(det.class_name, (200, 200, 200))
        thickness = CONFIG["box_thickness"]

        # Draw box
        cv2.rectangle(image, (x1, y1), (x2, y2), color, thickness)

        # Label with class, size, confidence, price
        currency = CONFIG["currency"]
        if det.price > 0:
            label = f"{det.class_name} ({det.size}) {det.confidence:.0%} {currency}{det.price:.2f}"
        else:
            label = f"{det.class_name} {det.confidence:.0%}"

        font = cv2.FONT_HERSHEY_SIMPLEX
        scale = CONFIG["font_scale"]
        (tw, th), baseline = cv2.getTextSize(label, font, scale, 1)

        # Label background
        cv2.rectangle(image, (x1, y1 - th - 10), (x1 + tw + 6, y1), color, -1)
        cv2.putText(image, label, (x1 + 3, y1 - 5), font, scale, (255, 255, 255), 2)

    return image


def _draw_receipt(detections: List[Detection], total: float,
                  model_name: str, inference_ms: float, img_height: int) -> np.ndarray:
    """Create a receipt panel as a numpy image."""
    w = CONFIG["receipt_width"]
    h = max(img_height, 500)
    receipt = np.ones((h, w, 3), dtype=np.uint8) * 245  # light gray bg

    font = cv2.FONT_HERSHEY_SIMPLEX
    currency = CONFIG["currency"]
    y = 30
    line_h = 28

    def put(text, y_pos, scale=0.55, color=(30, 30, 30), thickness=1):
        cv2.putText(receipt, text, (15, y_pos), font, scale, color, thickness)
        return y_pos + line_h

    # Header
    y = put("================================", y, 0.45, (100, 100, 100))
    y = put("   ECONOMY RICE CHECKOUT", y, 0.65, (0, 0, 0), 2)
    y = put("================================", y, 0.45, (100, 100, 100))
    y = put(f"  Model: {model_name}", y, 0.45, (80, 80, 80))
    y = put(f"  Time : {datetime.now().strftime('%Y-%m-%d %H:%M')}", y, 0.45, (80, 80, 80))
    y = put(f"  Speed: {inference_ms:.0f}ms", y, 0.45, (80, 80, 80))
    y = put("--------------------------------", y, 0.45, (150, 150, 150))

    # Items
    billable = [d for d in detections if d.price > 0]
    non_billable = [d for d in detections if d.price == 0]

    if billable:
        y = put("  ITEM          SIZE  PRICE", y, 0.45, (60, 60, 60))
        y = put("  ----          ----  -----", y, 0.40, (150, 150, 150))

        # Group by (class, size) for cleaner receipt
        grouped = defaultdict(lambda: {"count": 0, "unit_price": 0.0})
        for d in billable:
            key = (d.class_name, d.size)
            grouped[key]["count"] += 1
            grouped[key]["unit_price"] = d.price

        for (cls, size), info in sorted(grouped.items()):
            count = info["count"]
            unit  = info["unit_price"]
            line_total = unit * count
            qty_str = f"x{count}" if count > 1 else "  "
            y = put(f"  {cls:<12s}  {size}  {currency}{unit:.2f} {qty_str} = {currency}{line_total:.2f}", y, 0.42)
    else:
        y = put("  (No billable items detected)", y, 0.45, (150, 50, 50))

    if non_billable:
        y += 5
        y = put(f"  Plate detected: 1", y, 0.40, (120, 120, 120))

    # Subtotal
    y += 10
    y = put("================================", y, 0.45, (100, 100, 100))
    y = put(f"  SUBTOTAL: {currency}{total:.2f}", y, 0.7, (0, 0, 180), 2)
    y = put("================================", y, 0.45, (100, 100, 100))

    # Item count summary
    y += 5
    summary = Counter(d.class_name for d in detections)
    y = put(f"  Items: {dict(summary)}", y, 0.40, (100, 100, 100))

    # Footer
    y += 15
    y = put("  Thank you! Terima kasih!", y, 0.45, (80, 80, 80))

    return receipt


def _combine_image_receipt(image: np.ndarray, receipt: np.ndarray) -> np.ndarray:
    """Place image and receipt side by side, matching heights."""
    h1, h2 = image.shape[0], receipt.shape[0]
    target_h = max(h1, h2)

    if h1 < target_h:
        pad = np.ones((target_h - h1, image.shape[1], 3), dtype=np.uint8) * 220
        image = np.vstack([image, pad])
    if h2 < target_h:
        pad = np.ones((target_h - h2, receipt.shape[1], 3), dtype=np.uint8) * 245
        receipt = np.vstack([receipt, pad])

    return np.hstack([image, receipt])


def _print_receipt(result: CheckoutResult) -> None:
    """Print a clean text receipt to stdout."""
    c = CONFIG["currency"]
    print(f"\n{'='*50}")
    print(f"  🧾 ECONOMY RICE SMART CHECKOUT")
    print(f"{'='*50}")
    print(f"  Model    : {result.model_name}")
    print(f"  Image    : {os.path.basename(result.image_path)}")
    print(f"  Speed    : {result.inference_time_ms:.0f} ms")
    print(f"{'─'*50}")

    grouped = defaultdict(lambda: {"count": 0, "unit_price": 0.0, "size": ""})
    for d in result.billable_items:
        key = (d.class_name, d.size)
        grouped[key]["count"] += 1
        grouped[key]["unit_price"] = d.price
        grouped[key]["size"] = d.size

    if grouped:
        print(f"  {'Item':<12s}  {'Size':>4s}  {'Qty':>3s}  {'Unit':>7s}  {'Total':>8s}")
        print(f"  {'─'*12}  {'─'*4}  {'─'*3}  {'─'*7}  {'─'*8}")
        for (cls, size), info in sorted(grouped.items()):
            line_total = info["unit_price"] * info["count"]
            print(f"  {cls:<12s}  {size:>4s}  {info['count']:>3d}  {c}{info['unit_price']:>5.2f}  {c}{line_total:>6.2f}")
    else:
        print("  (No billable items detected)")

    plate_count = sum(1 for d in result.detections if d.class_name == "plate")
    if plate_count:
        print(f"\n  Plate: 1 detected")

    # Cropped items summary
    crops = result.cropped_images
    if crops:
        print(f"  🔍 Cropped food items: {len(crops)}")

    print(f"{'─'*50}")
    print(f"  💰 SUBTOTAL: {c}{result.total_price:.2f}")
    print(f"{'='*50}\n")


# ── 9. Display Helpers ────────────────────────────────────────────────────────

def show_result(result: CheckoutResult, width: int = 900) -> None:
    """Display the annotated image + receipt in Colab, plus cropped food items."""
    if result.annotated_image is None:
        print("  ⚠️  No annotated image to display")
        return

    # Save temporary file for display
    tmp_path = "/content/_checkout_result.jpg"
    cv2.imwrite(tmp_path, result.annotated_image)

    try:
        display(IPyImage(filename=tmp_path, width=width))
    except Exception:
        print(f"  (Image saved at {tmp_path})")

    # ── Display cropped food items ──
    crops = result.cropped_images
    if crops:
        num_crops = min(len(crops), 8)
        fig, axes = plt.subplots(1, num_crops, figsize=(3 * num_crops, 3))
        if num_crops == 1:
            axes = [axes]
        for i in range(num_crops):
            c_name, c_score, c_img = crops[i]
            # Convert BGR to RGB for matplotlib display
            if len(c_img.shape) == 3 and c_img.shape[2] == 3:
                c_img_rgb = cv2.cvtColor(c_img, cv2.COLOR_BGR2RGB)
            else:
                c_img_rgb = c_img
            axes[i].imshow(c_img_rgb)
            axes[i].axis('off')
            axes[i].set_title(f"{c_name.upper()}\nConf: {c_score:.2f}", color='blue', fontweight='bold')
        plt.suptitle("Detected Food Items (Cropped)", fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.show()


def save_result(result: CheckoutResult, output_dir: str = "/content/checkout_results") -> str:
    """Save annotated image, receipt, and cropped food items to disk."""
    os.makedirs(output_dir, exist_ok=True)
    stem = Path(result.image_path).stem
    timestamp = datetime.now().strftime("%H%M%S")
    filename = f"{stem}_{result.model_name.replace(' ', '_')}_{timestamp}.jpg"
    out_path = os.path.join(output_dir, filename)

    if result.annotated_image is not None:
        cv2.imwrite(out_path, result.annotated_image)
        print(f"  💾 Saved → {out_path}")

    # Save cropped food items
    crops = result.cropped_images
    if crops:
        crops_dir = os.path.join(output_dir, f"{stem}_crops")
        os.makedirs(crops_dir, exist_ok=True)
        for idx, (c_name, c_score, c_img) in enumerate(crops):
            crop_filename = f"{idx+1}_{c_name}_{c_score:.2f}.jpg"
            crop_path = os.path.join(crops_dir, crop_filename)
            cv2.imwrite(crop_path, c_img)
        print(f"  🔍 Saved {len(crops)} cropped items → {crops_dir}")

    return out_path


# ── 10. Batch Inference ───────────────────────────────────────────────────────

def batch_checkout(image_dir: str, detector, save_dir: str = "/content/checkout_results",
                   show: bool = True) -> List[CheckoutResult]:
    """Run checkout on all images in a directory."""
    IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
    images = sorted([
        os.path.join(image_dir, f)
        for f in os.listdir(image_dir)
        if Path(f).suffix.lower() in IMAGE_EXTS
    ])

    if not images:
        print(f"  ❌ No images found in {image_dir}")
        return []

    print(f"\n  📂 Processing {len(images)} images from {image_dir}")
    print(f"  Model: {detector.name}")
    print()

    results = []
    total_revenue = 0.0

    for i, img_path in enumerate(images, 1):
        print(f"  [{i}/{len(images)}] {os.path.basename(img_path)} ... ", end="")
        try:
            result = checkout(img_path, detector, verbose=False)
            results.append(result)
            total_revenue += result.total_price
            save_result(result, save_dir)
            print(f"✅  {len(result.detections)} items, {CONFIG['currency']}{result.total_price:.2f}")

            if show:
                show_result(result, width=800)
        except Exception as e:
            print(f"❌ {e}")

    print(f"\n  {'='*40}")
    print(f"  📊 Batch Summary: {len(results)} images processed")
    print(f"  💰 Total Revenue: {CONFIG['currency']}{total_revenue:.2f}")
    print(f"  ⚡ Avg Speed: {np.mean([r.inference_time_ms for r in results]):.0f} ms/image")
    print(f"  {'='*40}\n")

    return results


# ── 11. Model Comparison ─────────────────────────────────────────────────────

def compare_models(image_path: str, model_paths: Dict[str, str],
                   show: bool = True) -> Dict[str, CheckoutResult]:
    """
    Run the same image through multiple models and compare results.

    Usage:
        compare_models("/content/test.jpg", {
            "YOLOv8":      "/content/model_mixed_rice.pt",
            "RT-DETR":     "/content/model_rtdetr_mixed_rice.pt",
            "Faster R-CNN": "/content/faster_rcnn_mixed_rice.pth",
        })
    """
    print(f"\n{'='*60}")
    print(f"  🔬 Model Comparison: {os.path.basename(image_path)}")
    print(f"{'='*60}")

    results = {}

    for name, path in model_paths.items():
        if not os.path.exists(path):
            print(f"  ⚠️  {name}: model not found at {path}, skipping")
            continue

        print(f"\n  ── {name} ──")
        try:
            detector = load_detector(path)
            result = checkout(image_path, detector, verbose=True)
            results[name] = result

            if show:
                show_result(result, width=800)
        except Exception as e:
            print(f"  ❌ {name} failed: {e}")

    # Comparison table
    if len(results) > 1:
        c = CONFIG["currency"]
        print(f"\n  {'='*60}")
        print(f"  📊 COMPARISON TABLE")
        print(f"  {'─'*60}")
        print(f"  {'Model':<16s}  {'Items':>5s}  {'Total':>8s}  {'Speed':>8s}  {'Conf avg':>8s}")
        print(f"  {'─'*16}  {'─'*5}  {'─'*8}  {'─'*8}  {'─'*8}")

        for name, r in results.items():
            n_items = len(r.detections)
            avg_conf = np.mean([d.confidence for d in r.detections]) if r.detections else 0
            print(f"  {name:<16s}  {n_items:>5d}  {c}{r.total_price:>6.2f}  {r.inference_time_ms:>6.0f}ms  {avg_conf:>7.1%}")

        print(f"  {'='*60}\n")

    return results


# ── 12. Upload & Checkout (Interactive — Loop + Model Selection) ──────────────

def _discover_models() -> Dict[str, str]:
    """Return dict of available models {display_name: path}."""
    candidates = {
        "1 - YOLOv8":       CONFIG["yolo_model"],
        "2 - RT-DETR":      CONFIG["rtdetr_model"],
        "3 - Faster R-CNN":  CONFIG["frcnn_model"],
    }
    available = {}
    for name, path in candidates.items():
        if os.path.exists(path):
            available[name] = path
    return available


def _select_model(available_models: Dict[str, str]) -> Tuple[str, str]:
    """
    Prompt user to pick a model.  Returns (display_name, path).
    If only one model exists it is selected automatically.
    """
    names = list(available_models.keys())

    if len(names) == 0:
        raise FileNotFoundError("❌ No trained model found! Train a model first.")

    if len(names) == 1:
        print(f"  ℹ️  Only one model available — auto-selected {names[0]}")
        return names[0], available_models[names[0]]

    print("\n  ┌──────────────────────────────────┐")
    print("  │      SELECT A MODEL               │")
    print("  ├──────────────────────────────────┤")
    for name in names:
        tag = Path(available_models[name]).name
        print(f"  │  {name:<16s}  ({tag})")
    print("  └──────────────────────────────────┘")

    while True:
        choice = input("  Enter model number (1/2/3): ").strip()
        for name in names:
            if choice == name[0]:      # match on the leading digit
                return name, available_models[name]
        print("  ⚠️  Invalid choice. Please enter 1, 2, or 3.")


def upload_and_checkout() -> List[CheckoutResult]:
    """
    Interactive loop — repeatedly upload images and checkout.

    Each iteration you can:
      • Upload a new photo
      • Switch between YOLOv8 / RT-DETR / Faster R-CNN  (press m)
      • Quit  (press q)

    Usage (in Colab):
        results = upload_and_checkout()
    """
    # ── Discover available models ──
    available = _discover_models()
    if not available:
        raise FileNotFoundError("❌ No trained model found! Train a model first.")

    print(f"\n{'='*55}")
    print("  🛒  ECONOMY RICE SMART CHECKOUT — Interactive Mode")
    print(f"{'='*55}")
    print(f"  Available models: {len(available)}")
    for name, path in available.items():
        print(f"    • {name}  →  {Path(path).name}")

    # ── Let user pick the first model ──
    model_name, model_path = _select_model(available)
    print(f"\n  ⏳ Loading {model_name} ...")
    detector = load_detector(model_path)

    all_results: List[CheckoutResult] = []
    round_num = 0

    while True:
        round_num += 1
        print(f"\n{'─'*55}")
        print(f"  📷  Round {round_num}  |  Model: {detector.name}")
        print(f"{'─'*55}")
        print("  📤 Upload an image of a food plate ...")
        print("     (or type  m = switch model,  q = quit)")

        action = input("  Press Enter to upload, or type m/q: ").strip().lower()

        if action == "q":
            print("\n  👋 Exiting checkout. Thank you!")
            break

        if action == "m":
            model_name, model_path = _select_model(available)
            print(f"  ⏳ Loading {model_name} ...")
            detector = load_detector(model_path)
            round_num -= 1          # don't count model switch as a round
            continue

        # ── Upload image ──
        try:
            uploaded = colab_files.upload()
        except Exception as e:
            print(f"  ❌ Upload error: {e}")
            continue

        if not uploaded:
            print("  ❌ No file uploaded — skipping this round")
            continue

        filename = list(uploaded.keys())[0]
        img_path = f"/content/{filename}"

        # ── Run checkout ──
        print(f"\n  🔍 Running checkout with {detector.name} ...")
        try:
            result = checkout(img_path, detector, verbose=True)
            show_result(result)
            save_result(result)
            all_results.append(result)
        except Exception as e:
            print(f"  ❌ Checkout failed: {e}")
            continue

    # ── Session summary ──
    if all_results:
        c = CONFIG["currency"]
        total_revenue = sum(r.total_price for r in all_results)
        print(f"\n{'='*55}")
        print(f"  📊 SESSION SUMMARY  ({len(all_results)} images)")
        print(f"{'─'*55}")
        for i, r in enumerate(all_results, 1):
            fname = os.path.basename(r.image_path)
            print(f"  {i:>3d}. {fname:<25s} [{r.model_name}]  {c}{r.total_price:.2f}")
        print(f"{'─'*55}")
        print(f"  💰 GRAND TOTAL: {c}{total_revenue:.2f}")
        print(f"{'='*55}\n")

    return all_results


# ==============================================================================
# 🏁 QUICK START EXAMPLES
# ==============================================================================

def demo():
    """
    Quick demo — run this after training to test your models.
    Adjust paths as needed.
    """
    print(f"\n{'='*60}")
    print("  🎯 Smart Checkout Demo")
    print(f"{'='*60}")

    # Find a test image
    test_images = []
    for pattern in ["/content/food_dataset/**/val*/images/*.jpg",
                    "/content/food_dataset/**/test/images/*.jpg",
                    "/content/food_dataset/**/train/images/*.jpg"]:
        found = sorted(glob.glob(pattern, recursive=True))
        if found:
            test_images = found
            break

    if not test_images:
        print("  ❌ No test images found. Upload an image with upload_and_checkout()")
        return

    img_path = test_images[0]
    print(f"  Using: {img_path}\n")

    # Try each available model
    models = {}
    if os.path.exists(CONFIG["yolo_model"]):
        models["YOLOv8"] = CONFIG["yolo_model"]
    if os.path.exists(CONFIG["rtdetr_model"]):
        models["RT-DETR"] = CONFIG["rtdetr_model"]
    if os.path.exists(CONFIG["frcnn_model"]):
        models["Faster R-CNN"] = CONFIG["frcnn_model"]

    if not models:
        print("  ❌ No trained models found. Run training first!")
        return

    if len(models) > 1:
        compare_models(img_path, models)
    else:
        name, path = next(iter(models.items()))
        detector = load_detector(path)
        result = checkout(img_path, detector)
        show_result(result)


# ==============================================================================
# 📖 USAGE GUIDE (run any of these in a Colab cell)
# ==============================================================================
#
# ── Single Image ──────────────────────────────────────────
#   detector = load_detector("/content/model_mixed_rice.pt")
#   result = checkout("/content/test_food.jpg", detector)
#   show_result(result)
#
# ── Upload & Checkout (interactive loop) ──────────────────
#   results = upload_and_checkout()
#   # → Select model (1=YOLOv8, 2=RT-DETR, 3=Faster R-CNN)
#   # → Upload photo after photo (Enter to upload, m to switch model, q to quit)
#   # → Prints a session summary with grand total at the end
#
# ── Batch Processing ──────────────────────────────────────
#   detector = load_detector("/content/model_mixed_rice.pt")
#   results = batch_checkout("/content/test_images/", detector)
#
# ── Compare All Models ────────────────────────────────────
#   compare_models("/content/test.jpg", {
#       "YOLOv8":       "/content/model_mixed_rice.pt",
#       "RT-DETR":      "/content/model_rtdetr_mixed_rice.pt",
#       "Faster R-CNN": "/content/faster_rcnn_mixed_rice.pth",
#   })
#
# ── Access Cropped Food Items ─────────────────────────────
#   result = checkout("/content/test.jpg", detector)
#   for name, conf, crop_img in result.cropped_images:
#       print(f"  {name} ({conf:.2f})")
#       plt.imshow(cv2.cvtColor(crop_img, cv2.COLOR_BGR2RGB))
#       plt.show()
#
# ── Quick Demo ────────────────────────────────────────────
#   demo()
#
# ==============================================================================

if __name__ == "__main__":
    demo()